<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RefSurahSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['no_surah' => 1, 'nama_surah' => 'Al-Fatihah', 'nama_surah_arab' => 'الفاتحة', 'arti_surah' => 'Pembukaan', 'jumlah_ayat' => 7],
            ['no_surah' => 2, 'nama_surah' => 'Al-Baqarah', 'nama_surah_arab' => 'البقرة', 'arti_surah' => 'Sapi Betina', 'jumlah_ayat' => 286],
            ['no_surah' => 3, 'nama_surah' => 'Ali Imran', 'nama_surah_arab' => 'آل عمران', 'arti_surah' => 'Keluarga Imran', 'jumlah_ayat' => 200],
            ['no_surah' => 4, 'nama_surah' => 'An-Nisa', 'nama_surah_arab' => 'النساء', 'arti_surah' => 'Wanita', 'jumlah_ayat' => 176],
            ['no_surah' => 5, 'nama_surah' => 'Al-Maidah', 'nama_surah_arab' => 'المائدة', 'arti_surah' => 'Jamuan (Hidangan Makanan)', 'jumlah_ayat' => 120],
            ['no_surah' => 6, 'nama_surah' => 'Al-Anam', 'nama_surah_arab' => 'الأنعام', 'arti_surah' => 'Binatang Ternak', 'jumlah_ayat' => 165],
            ['no_surah' => 7, 'nama_surah' => 'Al-Araf', 'nama_surah_arab' => 'الأعراف', 'arti_surah' => 'Tempat yang Tertinggi', 'jumlah_ayat' => 206],
            ['no_surah' => 8, 'nama_surah' => 'Al-Anfal', 'nama_surah_arab' => 'الأنفال', 'arti_surah' => 'Harta Rampasan Perang', 'jumlah_ayat' => 75],
            ['no_surah' => 9, 'nama_surah' => 'At-Taubah', 'nama_surah_arab' => 'التوبة', 'arti_surah' => 'Pengampunan', 'jumlah_ayat' => 129],
            ['no_surah' => 10, 'nama_surah' => 'Yunus', 'nama_surah_arab' => 'يونس', 'arti_surah' => 'Nabi Yunus', 'jumlah_ayat' => 109],
            ['no_surah' => 11, 'nama_surah' => 'Hud', 'nama_surah_arab' => 'هود', 'arti_surah' => 'Nabi Hud', 'jumlah_ayat' => 123],
            ['no_surah' => 12, 'nama_surah' => 'Yusuf', 'nama_surah_arab' => 'يوسف', 'arti_surah' => 'Nabi Yusuf', 'jumlah_ayat' => 111],
            ['no_surah' => 13, 'nama_surah' => 'Ar-Rad', 'nama_surah_arab' => 'الرعد', 'arti_surah' => 'Guruh (Petir)', 'jumlah_ayat' => 43],
            ['no_surah' => 14, 'nama_surah' => 'Ibrahim', 'nama_surah_arab' => 'إبراهيم', 'arti_surah' => 'Nabi Ibrahim', 'jumlah_ayat' => 52],
            ['no_surah' => 15, 'nama_surah' => 'Al-Hijr', 'nama_surah_arab' => 'الحجر', 'arti_surah' => 'Al Hijr (Nama Gunung)', 'jumlah_ayat' => 99],
            ['no_surah' => 16, 'nama_surah' => 'An-Nahl', 'nama_surah_arab' => 'النحل', 'arti_surah' => 'Lebah', 'jumlah_ayat' => 128],
            ['no_surah' => 17, 'nama_surah' => 'Al-Isra', 'nama_surah_arab' => 'الإسراء', 'arti_surah' => 'Memperjalankan di Malam Hari', 'jumlah_ayat' => 111],
            ['no_surah' => 18, 'nama_surah' => 'Al-Kahfi', 'nama_surah_arab' => 'الكهف', 'arti_surah' => 'Penghuni-penghuni Gua', 'jumlah_ayat' => 110],
            ['no_surah' => 19, 'nama_surah' => 'Maryam', 'nama_surah_arab' => 'مريم', 'arti_surah' => 'Maryam (Maria)', 'jumlah_ayat' => 98],
            ['no_surah' => 20, 'nama_surah' => 'Taha', 'nama_surah_arab' => 'طه', 'arti_surah' => 'Ta Ha', 'jumlah_ayat' => 135],
            ['no_surah' => 21, 'nama_surah' => 'Al-Anbiya', 'nama_surah_arab' => 'الأنبياء', 'arti_surah' => 'Nabi-Nabi', 'jumlah_ayat' => 112],
            ['no_surah' => 22, 'nama_surah' => 'Al-Hajj', 'nama_surah_arab' => 'الحج', 'arti_surah' => 'Haji', 'jumlah_ayat' => 78],
            ['no_surah' => 23, 'nama_surah' => 'Al-Muminun', 'nama_surah_arab' => 'المؤمنون', 'arti_surah' => 'Orang-orang Mukmin', 'jumlah_ayat' => 118],
            ['no_surah' => 24, 'nama_surah' => 'An-Nur', 'nama_surah_arab' => 'النور', 'arti_surah' => 'Cahaya', 'jumlah_ayat' => 64],
            ['no_surah' => 25, 'nama_surah' => 'Al-Furqan', 'nama_surah_arab' => 'الفرقان', 'arti_surah' => 'Pembeda', 'jumlah_ayat' => 77],
            ['no_surah' => 26, 'nama_surah' => 'Asy-Syuara', 'nama_surah_arab' => 'الشعراء', 'arti_surah' => 'Penyair', 'jumlah_ayat' => 227],
            ['no_surah' => 27, 'nama_surah' => 'An-Naml', 'nama_surah_arab' => 'النمل', 'arti_surah' => 'Semut', 'jumlah_ayat' => 93],
            ['no_surah' => 28, 'nama_surah' => 'Al-Qasas', 'nama_surah_arab' => 'القصص', 'arti_surah' => 'Cerita', 'jumlah_ayat' => 88],
            ['no_surah' => 29, 'nama_surah' => 'Al-Ankabut', 'nama_surah_arab' => 'العنكبوت', 'arti_surah' => 'Laba-laba', 'jumlah_ayat' => 69],
            ['no_surah' => 30, 'nama_surah' => 'Ar-Rum', 'nama_surah_arab' => 'الروم', 'arti_surah' => 'Bangsa Romawi', 'jumlah_ayat' => 60],
            ['no_surah' => 31, 'nama_surah' => 'Luqman', 'nama_surah_arab' => 'لقمان', 'arti_surah' => 'Keluarga Luqman', 'jumlah_ayat' => 34],
            ['no_surah' => 32, 'nama_surah' => 'As-Sajdah', 'nama_surah_arab' => 'السجدة', 'arti_surah' => 'Sajdah', 'jumlah_ayat' => 30],
            ['no_surah' => 33, 'nama_surah' => 'Al-Ahzab', 'nama_surah_arab' => 'الأحزاب', 'arti_surah' => 'Golongan-Golongan yang Bersekutu', 'jumlah_ayat' => 73],
            ['no_surah' => 34, 'nama_surah' => 'Saba', 'nama_surah_arab' => 'سبأ', 'arti_surah' => 'Kaum Saba', 'jumlah_ayat' => 54],
            ['no_surah' => 35, 'nama_surah' => 'Fatir', 'nama_surah_arab' => 'فاطر', 'arti_surah' => 'Pencipta', 'jumlah_ayat' => 45],
            ['no_surah' => 36, 'nama_surah' => 'Yasin', 'nama_surah_arab' => 'يس', 'arti_surah' => 'Yaasiin', 'jumlah_ayat' => 83],
            ['no_surah' => 37, 'nama_surah' => 'As-Saffat', 'nama_surah_arab' => 'الصافات', 'arti_surah' => 'Barisan-barisan', 'jumlah_ayat' => 182],
            ['no_surah' => 38, 'nama_surah' => 'Sad', 'nama_surah_arab' => 'ص', 'arti_surah' => 'Shaad', 'jumlah_ayat' => 88],
            ['no_surah' => 39, 'nama_surah' => 'Az-Zumar', 'nama_surah_arab' => 'الزمر', 'arti_surah' => 'Rombongan-rombongan', 'jumlah_ayat' => 75],
            ['no_surah' => 40, 'nama_surah' => 'Ghafir', 'nama_surah_arab' => 'غافر', 'arti_surah' => 'Yang Mengampuni', 'jumlah_ayat' => 85],
            ['no_surah' => 41, 'nama_surah' => 'Fussilat', 'nama_surah_arab' => 'فصلت', 'arti_surah' => 'Yang Dijelaskan', 'jumlah_ayat' => 54],
            ['no_surah' => 42, 'nama_surah' => 'Asy-Syura', 'nama_surah_arab' => 'الشورى', 'arti_surah' => 'Musyawarah', 'jumlah_ayat' => 53],
            ['no_surah' => 43, 'nama_surah' => 'Az-Zukhruf', 'nama_surah_arab' => 'الزخرف', 'arti_surah' => 'Perhiasan', 'jumlah_ayat' => 89],
            ['no_surah' => 44, 'nama_surah' => 'Ad-Dukhan', 'nama_surah_arab' => 'الدخان', 'arti_surah' => 'Kabut', 'jumlah_ayat' => 59],
            ['no_surah' => 45, 'nama_surah' => 'Al-Jasiyah', 'nama_surah_arab' => 'الجاثية', 'arti_surah' => 'Yang Berlutut', 'jumlah_ayat' => 37],
            ['no_surah' => 46, 'nama_surah' => 'Al-Ahqaf', 'nama_surah_arab' => 'الأحقاف', 'arti_surah' => 'Bukit-bukit Pasir', 'jumlah_ayat' => 35],
            ['no_surah' => 47, 'nama_surah' => 'Muhammad', 'nama_surah_arab' => 'محمد', 'arti_surah' => 'Nabi Muhammad', 'jumlah_ayat' => 38],
            ['no_surah' => 48, 'nama_surah' => 'Al-Fath', 'nama_surah_arab' => 'الفتح', 'arti_surah' => 'Kemenangan', 'jumlah_ayat' => 29],
            ['no_surah' => 49, 'nama_surah' => 'Al-Hujurat', 'nama_surah_arab' => 'الحجرات', 'arti_surah' => 'Kamar-kamar', 'jumlah_ayat' => 18],
            ['no_surah' => 50, 'nama_surah' => 'Qaf', 'nama_surah_arab' => 'ق', 'arti_surah' => 'Qaaf', 'jumlah_ayat' => 45],
            ['no_surah' => 51, 'nama_surah' => 'Az-Zariyat', 'nama_surah_arab' => 'الذاريات', 'arti_surah' => 'Angin yang Menerbangkan', 'jumlah_ayat' => 60],
            ['no_surah' => 52, 'nama_surah' => 'At-Tur', 'nama_surah_arab' => 'الطور', 'arti_surah' => 'Bukit', 'jumlah_ayat' => 49],
            ['no_surah' => 53, 'nama_surah' => 'An-Najm', 'nama_surah_arab' => 'النجم', 'arti_surah' => 'Bintang', 'jumlah_ayat' => 62],
            ['no_surah' => 54, 'nama_surah' => 'Al-Qamar', 'nama_surah_arab' => 'القمر', 'arti_surah' => 'Bulan', 'jumlah_ayat' => 55],
            ['no_surah' => 55, 'nama_surah' => 'Ar-Rahman', 'nama_surah_arab' => 'الرحمن', 'arti_surah' => 'Yang Maha Pemurah', 'jumlah_ayat' => 78],
            ['no_surah' => 56, 'nama_surah' => 'Al-Waqiah', 'nama_surah_arab' => 'الواقعة', 'arti_surah' => 'Hari Kiamat', 'jumlah_ayat' => 96],
            ['no_surah' => 57, 'nama_surah' => 'Al-Hadid', 'nama_surah_arab' => 'الحديد', 'arti_surah' => 'Besi', 'jumlah_ayat' => 29],
            ['no_surah' => 58, 'nama_surah' => 'Al-Mujadilah', 'nama_surah_arab' => 'المجادلة', 'arti_surah' => 'Wanita yang Mengajukan Gugatan', 'jumlah_ayat' => 22],
            ['no_surah' => 59, 'nama_surah' => 'Al-Hasyr', 'nama_surah_arab' => 'الحشر', 'arti_surah' => 'Pengusiran', 'jumlah_ayat' => 24],
            ['no_surah' => 60, 'nama_surah' => 'Al-Mumtahanah', 'nama_surah_arab' => 'الممتحنة', 'arti_surah' => 'Wanita yang Diuji', 'jumlah_ayat' => 13],
            ['no_surah' => 61, 'nama_surah' => 'As-Saff', 'nama_surah_arab' => 'الصف', 'arti_surah' => 'Satu Barisan', 'jumlah_ayat' => 14],
            ['no_surah' => 62, 'nama_surah' => 'Al-Jumuah', 'nama_surah_arab' => 'الجمعة', 'arti_surah' => 'Hari Jum\'at', 'jumlah_ayat' => 11],
            ['no_surah' => 63, 'nama_surah' => 'Al-Munafiqun', 'nama_surah_arab' => 'المنافقون', 'arti_surah' => 'Orang-orang yang Munafik', 'jumlah_ayat' => 11],
            ['no_surah' => 64, 'nama_surah' => 'At-Taghabun', 'nama_surah_arab' => 'التغابن', 'arti_surah' => 'Hari Dinampakkan Kesalahan-kesalahan', 'jumlah_ayat' => 18],
            ['no_surah' => 65, 'nama_surah' => 'At-Talaq', 'nama_surah_arab' => 'الطلاق', 'arti_surah' => 'Talak', 'jumlah_ayat' => 12],
            ['no_surah' => 66, 'nama_surah' => 'At-Tahrim', 'nama_surah_arab' => 'التحريم', 'arti_surah' => 'Mengharamkan', 'jumlah_ayat' => 12],
            ['no_surah' => 67, 'nama_surah' => 'Al-Mulk', 'nama_surah_arab' => 'الملك', 'arti_surah' => 'Kerajaan', 'jumlah_ayat' => 30],
            ['no_surah' => 68, 'nama_surah' => 'Al-Qalam', 'nama_surah_arab' => 'القلم', 'arti_surah' => 'Pena', 'jumlah_ayat' => 52],
            ['no_surah' => 69, 'nama_surah' => 'Al-Haqqah', 'nama_surah_arab' => 'الحاقة', 'arti_surah' => 'Hari Kiamat', 'jumlah_ayat' => 52],
            ['no_surah' => 70, 'nama_surah' => 'Al-Maarij', 'nama_surah_arab' => 'المعارج', 'arti_surah' => 'Tempat Naik', 'jumlah_ayat' => 44],
            ['no_surah' => 71, 'nama_surah' => 'Nuh', 'nama_surah_arab' => 'نوح', 'arti_surah' => 'Nabi Nuh', 'jumlah_ayat' => 28],
            ['no_surah' => 72, 'nama_surah' => 'Al-Jinn', 'nama_surah_arab' => 'الجن', 'arti_surah' => 'Jin', 'jumlah_ayat' => 28],
            ['no_surah' => 73, 'nama_surah' => 'Al-Muzzammil', 'nama_surah_arab' => 'المزمل', 'arti_surah' => 'Orang yang Berselimut', 'jumlah_ayat' => 20],
            ['no_surah' => 74, 'nama_surah' => 'Al-Muddassir', 'nama_surah_arab' => 'المدثر', 'arti_surah' => 'Orang yang Berkemul', 'jumlah_ayat' => 56],
            ['no_surah' => 75, 'nama_surah' => 'Al-Qiyamah', 'nama_surah_arab' => 'القيامة', 'arti_surah' => 'Kiamat', 'jumlah_ayat' => 40],
            ['no_surah' => 76, 'nama_surah' => 'Al-Insan', 'nama_surah_arab' => 'الإنسان', 'arti_surah' => 'Manusia', 'jumlah_ayat' => 31],
            ['no_surah' => 77, 'nama_surah' => 'Al-Mursalat', 'nama_surah_arab' => 'المرسلات', 'arti_surah' => 'Malaikat Yang Diutus', 'jumlah_ayat' => 50],
            ['no_surah' => 78, 'nama_surah' => 'An-Naba', 'nama_surah_arab' => 'النبأ', 'arti_surah' => 'Berita Besar', 'jumlah_ayat' => 40],
            ['no_surah' => 79, 'nama_surah' => 'An-Naziat', 'nama_surah_arab' => 'النازعات', 'arti_surah' => 'Malaikat-Malaikat Yang Mencabut', 'jumlah_ayat' => 46],
            ['no_surah' => 80, 'nama_surah' => 'Abasa', 'nama_surah_arab' => 'عبس', 'arti_surah' => 'Ia Bermuka Masam', 'jumlah_ayat' => 42],
            ['no_surah' => 81, 'nama_surah' => 'At-Takwir', 'nama_surah_arab' => 'التكوير', 'arti_surah' => 'Menggulung', 'jumlah_ayat' => 29],
            ['no_surah' => 82, 'nama_surah' => 'Al-Infitar', 'nama_surah_arab' => 'الانفطار', 'arti_surah' => 'Terbelah', 'jumlah_ayat' => 19],
            ['no_surah' => 83, 'nama_surah' => 'Al-Mutaffifin', 'nama_surah_arab' => 'المطففين', 'arti_surah' => 'Orang-orang yang Curang', 'jumlah_ayat' => 36],
            ['no_surah' => 84, 'nama_surah' => 'Al-Insyiqaq', 'nama_surah_arab' => 'الانشقاق', 'arti_surah' => 'Terbelah', 'jumlah_ayat' => 25],
            ['no_surah' => 85, 'nama_surah' => 'Al-Buruj', 'nama_surah_arab' => 'البروج', 'arti_surah' => 'Gugusan Bintang', 'jumlah_ayat' => 22],
            ['no_surah' => 86, 'nama_surah' => 'At-Tariq', 'nama_surah_arab' => 'الطارق', 'arti_surah' => 'Yang Datang di Malam Hari', 'jumlah_ayat' => 17],
            ['no_surah' => 87, 'nama_surah' => 'Al-Ala', 'nama_surah_arab' => 'الأعلى', 'arti_surah' => 'Yang Paling Tinggi', 'jumlah_ayat' => 19],
            ['no_surah' => 88, 'nama_surah' => 'Al-Ghasyiyah', 'nama_surah_arab' => 'الغاشية', 'arti_surah' => 'Hari Pembalasan', 'jumlah_ayat' => 26],
            ['no_surah' => 89, 'nama_surah' => 'Al-Fajr', 'nama_surah_arab' => 'الفجر', 'arti_surah' => 'Fajar', 'jumlah_ayat' => 30],
            ['no_surah' => 90, 'nama_surah' => 'Al-Balad', 'nama_surah_arab' => 'البلد', 'arti_surah' => 'Negeri', 'jumlah_ayat' => 20],
            ['no_surah' => 91, 'nama_surah' => 'Asy-Syams', 'nama_surah_arab' => 'الشمس', 'arti_surah' => 'Matahari', 'jumlah_ayat' => 15],
            ['no_surah' => 92, 'nama_surah' => 'Al-Lail', 'nama_surah_arab' => 'الليل', 'arti_surah' => 'Malam', 'jumlah_ayat' => 21],
            ['no_surah' => 93, 'nama_surah' => 'Ad-Duha', 'nama_surah_arab' => 'الضحى', 'arti_surah' => 'Waktu Matahari Sepenggalahan Naik (Dhuha)', 'jumlah_ayat' => 11],
            ['no_surah' => 94, 'nama_surah' => 'Al-Insyirah', 'nama_surah_arab' => 'الشرح', 'arti_surah' => 'Melapangkan', 'jumlah_ayat' => 8],
            ['no_surah' => 95, 'nama_surah' => 'At-Tin', 'nama_surah_arab' => 'التين', 'arti_surah' => 'Buah Tin', 'jumlah_ayat' => 8],
            ['no_surah' => 96, 'nama_surah' => 'Al-Alaq', 'nama_surah_arab' => 'العلق', 'arti_surah' => 'Segumpal Darah', 'jumlah_ayat' => 19],
            ['no_surah' => 97, 'nama_surah' => 'Al-Qadr', 'nama_surah_arab' => 'القدر', 'arti_surah' => 'Kemuliaan', 'jumlah_ayat' => 5],
            ['no_surah' => 98, 'nama_surah' => 'Al-Bayyinah', 'nama_surah_arab' => 'البينة', 'arti_surah' => 'Pembuktian', 'jumlah_ayat' => 8],
            ['no_surah' => 99, 'nama_surah' => 'Az-Zalzalah', 'nama_surah_arab' => 'الزلزلة', 'arti_surah' => 'Kegoncangan', 'jumlah_ayat' => 8],
            ['no_surah' => 100, 'nama_surah' => 'Al-Adiyat', 'nama_surah_arab' => 'العاديات', 'arti_surah' => 'Berlari Kencang', 'jumlah_ayat' => 11],
            ['no_surah' => 101, 'nama_surah' => 'Al-Qariah', 'nama_surah_arab' => 'القارعة', 'arti_surah' => 'Hari Kiamat', 'jumlah_ayat' => 11],
            ['no_surah' => 102, 'nama_surah' => 'At-Takasur', 'nama_surah_arab' => 'التكاثر', 'arti_surah' => 'Bermegah-megahan', 'jumlah_ayat' => 8],
            ['no_surah' => 103, 'nama_surah' => 'Al-Asr', 'nama_surah_arab' => 'العصر', 'arti_surah' => 'Masa', 'jumlah_ayat' => 3],
            ['no_surah' => 104, 'nama_surah' => 'Al-Humazah', 'nama_surah_arab' => 'الهمزة', 'arti_surah' => 'Pengumpat', 'jumlah_ayat' => 9],
            ['no_surah' => 105, 'nama_surah' => 'Al-Fil', 'nama_surah_arab' => 'الفيل', 'arti_surah' => 'Gajah', 'jumlah_ayat' => 5],
            ['no_surah' => 106, 'nama_surah' => 'Quraisy', 'nama_surah_arab' => 'قريش', 'arti_surah' => 'Suku Quraisy', 'jumlah_ayat' => 4],
            ['no_surah' => 107, 'nama_surah' => 'Al-Maun', 'nama_surah_arab' => 'الماعون', 'arti_surah' => 'Barang-barang yang Berguna', 'jumlah_ayat' => 7],
            ['no_surah' => 108, 'nama_surah' => 'Al-Kautsar', 'nama_surah_arab' => 'الكوثر', 'arti_surah' => 'Nikmat yang Berlimpah', 'jumlah_ayat' => 3],
            ['no_surah' => 109, 'nama_surah' => 'Al-Kafirun', 'nama_surah_arab' => 'الكافرون', 'arti_surah' => 'Orang-orang Kafir', 'jumlah_ayat' => 6],
            ['no_surah' => 110, 'nama_surah' => 'An-Nasr', 'nama_surah_arab' => 'النصر', 'arti_surah' => 'Pertolongan', 'jumlah_ayat' => 3],
            ['no_surah' => 111, 'nama_surah' => 'Al-Lahab', 'nama_surah_arab' => 'المسد', 'arti_surah' => 'Gejolak Api', 'jumlah_ayat' => 5],
            ['no_surah' => 112, 'nama_surah' => 'Al-Ikhlas', 'nama_surah_arab' => 'الإخلاص', 'arti_surah' => 'Ikhlas', 'jumlah_ayat' => 4],
            ['no_surah' => 113, 'nama_surah' => 'Al-Falaq', 'nama_surah_arab' => 'الفلق', 'arti_surah' => 'Waktu Subuh', 'jumlah_ayat' => 5],
            ['no_surah' => 114, 'nama_surah' => 'An-Nas', 'nama_surah_arab' => 'الناس', 'arti_surah' => 'Manusia', 'jumlah_ayat' => 6],
        ];

        // Kosongkan tabel (Opsional, hapus baris ini jika tidak ingin mereset tabel lama)
        $this->db->table('ref_surah')->truncate();

        // Insert massal 114 data
        $this->db->table('ref_surah')->insertBatch($data);

        echo "Alhamdulillah, 114 Surah berhasil ditambahkan ke tabel ref_surah!\n";
    }
}